---
version: '3.7'

x-crdb-base: &crdb-base
  image: cockroachdb/cockroach:latest-v21.2
  networks:
    - default

services:
  db:
    <<: *crdb-base
    restart: on-failure
    ports:
      - "127.0.0.1:26257:26257"
      - "127.0.0.1:8080:8080"
    command: start-single-node --insecure
  db-init:
    <<: *crdb-base
    restart: 'no'
    depends_on:
      - db
    command: workload init movr 

networks:
  default:
    name: cockroach
